services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=meupet
      - MYSQL_ROOT_PASSWORD=ThePassword
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
